# Set theme
#remote_theme: daviddarnes/alembic@main
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

#compress_html:
#  clippings: all

twitter:
  username: valeria_kebets # jekyll-seo-tag > Owner's twitter username

author: Valeria Kebets # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Valeria Kebets # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/valeria_kebets
    - https://www.linkedin.com/in/valkebets/
    - https://github.com/valkebets

# Site settings
url: 'https://valkebets.github.io/'
baseurl: ''
title: 'Valeria Kebets'
description: ''
permalink: pretty

# site verification
#webmaster_verifications:
#  google: lB694ugK6e26p5fJs37qYbdvaozzE4dr219OLEdjgAI

# Pagination
paginate: 5
#paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Research
  url: /research/
- title: CV
  url: /cv/
  link: "/cv.html"
 #link: /assets/docs/CV_VK_2022-05.pdf
 # name: Curriculum Vitae (PDF)

# Footer nav
# navigation_footer:
#   Back to top: "#top"

# Site credits
navigation_footer:
    Adopted Alembic Theme: https://alembic.darn.es/

# Collections
collections:
  posts:
    title: Research
    output: true
    description: "Here are some of my research projects"
#     feature_text: |
#       Welcome to my blog
#    feature_image: "/assets/img/home_cover.jpg"

contact:
  github:     https://github.com/valkebets
  linkedin:   https://www.linkedin.com/in/valkebets/
  twitter:    https://twitter.com/valeria_kebets
