source "https://rubygems.org"

gem "jekyll", "~> 4.2.2"
gem "jekyll-sitemap", "~> 1.4.0"
gem "jekyll-mentions", "~> 1.6.0"
gem "jekyll-paginate", "~> 1.1.0"
gem "jekyll-seo-tag", "~> 2.6.1"
gem "jekyll-redirect-from", "~> 0.16.0"
gem "jekyll-feed", "~> 0.16.0"
gem "jekyll-commonmark", "~> 1.3.1"
gem "jekyll-include-cache", "~> 0.2.1"
gem "jemoji", "~> 0.12.0"
gem "jekyll-remote-theme", "~> 0.4.3"
gem "webrick", "~> 1.7.0"
